### ISSUE TITLE
Support for meal plan entry sharing

### ISSUE THREAD

**Issue by fz72** [aimok04/kitshn#19]
kitshn Version: 1.0.0-alpha.9

Hey,
thanks for this nice app.
It works great.
Is it possible to add the ability to share the mealplan with other users.

**Comment by aimok04** [comment]
Hi!
This isn't really a priority for me now because this is a setting you might just need to change once or twice on the web UI.
This surely is possible, and I might add a page dedicated to settings like this further down the line, but the main goal right now is to implement main features that are often used.

**Comment by aimok04** [comment]
Hey, I just noticed that you can also share individual meal plan entries and this would of course be a nice feature to implement. 😅

**Comment by fz72** [comment]
Hey, sorry for my late response.
Yes, I think the option on the website set the default settings for sharing meal plan entries.
It seems the default sharing settings are not taken into account for new entries.
The intention for this issue was not to change the setting in the app but to use the default share settings for new entries.

**Comment by aimok04** [comment]
Oh, ok. I don't really use that feature, and I thought that Tandoor would automatically apply the default setting when adding a new entry with the API. I will surely take a look into this!

**Comment by aimok04** [comment]
Hey @fz72 
Finally had some time to resolve this. I will release a new version tomorrow!
