### ISSUE TITLE
Display Properties

### ISSUE THREAD

**Issue by lukasspettel** [aimok04/kitshn#24]
It would be amazing to have an option to display custom properties defined in tandoor (nutritional value, etc).

Here is how its currently displayed in Tandoor:

![327084496-14345363-83dc-4b0e-9d44-f950dcacdb41](https://github.com/user-attachments/assets/215b2310-bfdc-45d9-9cda-0b07054672c7)

**Comment by aimok04** [comment]
Hey @lukasspettel 👋

Since I had some spare time and also thought it would be a good addition, I added it.
It works similarly to the Tandoor card.

Again: Although I have already tested this, it would be great to hear from you if this also works with your data as expected :)

![image](https://github.com/user-attachments/assets/3d1219f4-24a7-4d73-9890-6a4b62dabfe7)

**Comment by lukasspettel** [comment]
Looks amazing, thank you! One more question: Could you change formatting to decimal numbers or make fractions optional in the settings for this card? Would increase readability for some custom properties (e.g. price).

![Screenshot_20241029_144143_kitshn](https://github.com/user-attachments/assets/08d8a922-c43f-4441-a54b-1a991d732a51)

**Comment by aimok04** [comment]
Hi, yeah good idea. Going to add this for the next release!
