### ISSUE TITLE
[Bug] The time isn't imported correct when it's separated with comma (,)

### ISSUE THREAD

**Issue by DrDustwolf** [aimok04/kitshn#32]
[Bug] Commas are creating problems when importing a receipe

The time isn't imported correctly when hours and minutes are separated with a comma (,) as it's usual in german syntax.

For example 1,5 hours is imported as 15 hours! If you cook it this long you've got cinders instead of food.
![Screenshot_20241211-081902_Iceraven](https://github.com/user-attachments/assets/41f267f8-7566-4f92-9f50-b30e91a73df6)
![Screenshot_20241211-080447_kitshn](https://github.com/user-attachments/assets/36a17ae9-dcd4-4448-9071-93fe60de1168)

The Ingredients list gets also corrupted because of commas. See in the screenshot for details.
![Screenshot_20241211-080756_Iceraven](https://github.com/user-attachments/assets/50c9b844-015c-441f-8903-7c67eae934a8)

![Screenshot_20241211-080806_kitshn](https://github.com/user-attachments/assets/d702a81f-684f-4183-bf69-7902ca117082)

The marked time that's displayed in another color inside the description text in the steps is not recognized correctly when theres an hyphen between two figures.
See the screenshots for details.
![Screenshot_20241211-082312_Iceraven](https://github.com/user-attachments/assets/15fe2fc5-3852-4c17-a90a-ffed8f68569e)
![Screenshot_20241211-082242_kitshn](https://github.com/user-attachments/assets/44594354-4b20-45c6-a3e5-b9165a7d2a7c)

Here is the link to the the receipe I imported:
**https://www.einfachkochen.de/rezepte/entenbraten-das-beste-rezept**

**Comment by aimok04** [comment]
Hi,

The app doesn't parse recipes. That is handled by the server application. However this is also not the fault of TandoorRecipes, since the website itself returns the data like this.

![Screenshot_20241211-122614.png](https://github.com/user-attachments/assets/e7e17d03-30de-44ee-961c-12fe17aa1d6c)

This is something for the website owners to fix!

**Comment by DrDustwolf** [comment]
The website owner surely doesn't care about Tandoor or kitshn...

**Comment by DrDustwolf** [comment]
> This is something for the website owners to fix!

Have you (as the developer of kitshn) at least contacted them about this?

**Comment by aimok04** [comment]
> The website owners surely doesn't care about Tandoor or kitshn. Why should they?

This is not a problem relating to Tandoor nor kitshn.

> Have you (as the developer of kitshn) at least contacted them about this?

No, and I also don't care about this issue because this is not related to my software. 

> It's something that's true for most german receipes!
That's simply not true. Tandoor is developed by Germans and many users are also German speaking. Of course, not every website is supported — this is obviously impossible. But it shows that you have NO clue how time intensive it would be to support websites individually: that's why we have web standard's for that. If a website owner implements a standard badly, it's clearly his fault.

---

Have some attitude, man. This is not a big cooperation gaining millions of dollars. Tandoor and kitshn are developed as hobbies and are free to use by everybody. I think you are underestimating how much time goes into developing software. We also have different things to do because THIS ISN'T A FULL-TIME JOB. 

If this issue makes you mad: Go learn to code and open a PR for the SERVER that is actually handling parsing.
Or: just edit the recipes on the website. It isn't that hard to open a web browser.

You don't need to answer. I will not change my mind about this.
